### ISSUE TITLE
Use predefined variable instead hard coded project variable

### ISSUE THREAD

**Issue by derf974** [derf974/AZpipelinesViewer#2]
In build.yml workflow:
```yaml
      - run: npm run build
        env:
          PUBLIC_URL: "/AZpipelinesViewer" # TODO : Should be a predefinined variable
```
